language: node_js
sudo: true
node_js:
  - "7"

install:
  - npm install
  - webdriver-manager update

script:
  - npm test

notifications:
  email:
    recipients:
      - one@example.com
      - other@example.com
    on_success: always # default: change
    on_failure: always # default: always
